[package]
name = "decompiler_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
iced-x86 = "1.21.0"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
decompiler = { path = "../decompiler", features = ["trace"] }
anyhow = "1.0.99"
serde = "1.0.228"
serde_json = "1.0.145"
